import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(script_dir, os.pardir))
output_dir = os.path.join(project_root, '3_outputs')
screenshot_dir = os.path.join(project_root, '4_screenshots')

os.makedirs(screenshot_dir, exist_ok=True)

df = pd.read_csv(os.path.join(output_dir, 'cleaned_airbnb.csv'))

plt.style.use('seaborn-v0_8-darkgrid')

print("Generating visualizations...")

plt.figure(figsize=(12, 6))
group_counts = df['neighbourhood_group'].value_counts()
colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7']
bars = plt.bar(group_counts.index, group_counts.values, color=colors, edgecolor='black')
plt.title('Listings by Neighbourhood Group', fontsize=16, fontweight='bold')
plt.xlabel('Neighbourhood Group', fontsize=12)
plt.ylabel('Number of Listings', fontsize=12)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 50, f'{int(height)}', ha='center')
plt.tight_layout()
plt.savefig(os.path.join(screenshot_dir, 'listings_by_neighbourhood.png'), dpi=300, bbox_inches='tight')
plt.close()
print("✓ listings_by_neighbourhood.png saved")

plt.figure(figsize=(12, 6))
avg_price_group = df.groupby('neighbourhood_group')['price'].mean().sort_values()
bars = plt.barh(avg_price_group.index, avg_price_group.values, color=['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7'])
plt.title('Average Price by Neighbourhood Group', fontsize=16, fontweight='bold')
plt.xlabel('Average Price ($)', fontsize=12)
plt.ylabel('Neighbourhood Group', fontsize=12)
for bar in bars:
    width = bar.get_width()
    plt.text(width + 2, bar.get_y() + bar.get_height()/2, f'${width:.0f}', va='center')
plt.tight_layout()
plt.savefig(os.path.join(screenshot_dir, 'avg_price_by_neighbourhood.png'), dpi=300, bbox_inches='tight')
plt.close()
print("✓ avg_price_by_neighbourhood.png saved")

plt.figure(figsize=(10, 8))
room_counts = df['room_type'].value_counts()
colors = ['#FF6B6B', '#4ECDC4', '#45B7D1']
plt.pie(room_counts.values, labels=room_counts.index, autopct='%1.1f%%', colors=colors, startangle=90)
plt.title('Room Type Distribution', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.savefig(os.path.join(screenshot_dir, 'room_type_pie.png'), dpi=300, bbox_inches='tight')
plt.close()
print("✓ room_type_pie.png saved")

plt.figure(figsize=(12, 6))
avg_price_room = df.groupby(['neighbourhood_group', 'room_type'])['price'].mean().unstack()
avg_price_room.plot(kind='bar', figsize=(12, 6), color=['#FF6B6B', '#4ECDC4', '#45B7D1'])
plt.title('Average Price by Neighbourhood and Room Type', fontsize=16, fontweight='bold')
plt.xlabel('Neighbourhood Group', fontsize=12)
plt.ylabel('Average Price ($)', fontsize=12)
plt.xticks(rotation=0)
plt.legend(title='Room Type')
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(screenshot_dir, 'price_neighbourhood_room.png'), dpi=300, bbox_inches='tight')
plt.close()
print("✓ price_neighbourhood_room.png saved")

plt.figure(figsize=(12, 6))
df_sorted = df.sort_values('price', ascending=False)
top_10 = df_sorted.head(10)
bars = plt.barh(top_10['name'].str[:30], top_10['price'], color='#FF6B6B', edgecolor='black')
plt.title('Top 10 Most Expensive Listings', fontsize=16, fontweight='bold')
plt.xlabel('Price ($)', fontsize=12)
plt.ylabel('Listing Name', fontsize=12)
for bar in bars:
    width = bar.get_width()
    plt.text(width + 5, bar.get_y() + bar.get_height()/2, f'${width:.0f}', va='center')
plt.tight_layout()
plt.savefig(os.path.join(screenshot_dir, 'top_10_expensive.png'), dpi=300, bbox_inches='tight')
plt.close()
print("✓ top_10_expensive.png saved")

plt.figure(figsize=(12, 6))
plt.hist(df['price'], bins=50, color='#4ECDC4', edgecolor='black', alpha=0.7)
plt.title('Price Distribution', fontsize=16, fontweight='bold')
plt.xlabel('Price ($)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.xlim(0, 500)
plt.axvline(df['price'].mean(), color='red', linestyle='dashed', label=f'Mean: ${df["price"].mean():.0f}')
plt.axvline(df['price'].median(), color='blue', linestyle='dashed', label=f'Median: ${df["price"].median():.0f}')
plt.legend()
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(screenshot_dir, 'price_distribution.png'), dpi=300, bbox_inches='tight')
plt.close()
print("✓ price_distribution.png saved")

plt.figure(figsize=(12, 6))
avg_reviews_group = df.groupby('neighbourhood_group')['number_of_reviews'].mean().sort_values()
bars = plt.bar(avg_reviews_group.index, avg_reviews_group.values, color=['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7'])
plt.title('Average Reviews by Neighbourhood Group', fontsize=16, fontweight='bold')
plt.xlabel('Neighbourhood Group', fontsize=12)
plt.ylabel('Average Number of Reviews', fontsize=12)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 0.5, f'{height:.1f}', ha='center')
plt.tight_layout()
plt.savefig(os.path.join(screenshot_dir, 'avg_reviews_neighbourhood.png'), dpi=300, bbox_inches='tight')
plt.close()
print("✓ avg_reviews_neighbourhood.png saved")

plt.figure(figsize=(12, 6))
availability_by_group = df.groupby('neighbourhood_group')['availability_365'].mean().sort_values()
bars = plt.bar(availability_by_group.index, availability_by_group.values, color=['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7'])
plt.title('Average Availability by Neighbourhood Group', fontsize=16, fontweight='bold')
plt.xlabel('Neighbourhood Group', fontsize=12)
plt.ylabel('Average Availability (days/year)', fontsize=12)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 2, f'{height:.0f}', ha='center')
plt.tight_layout()
plt.savefig(os.path.join(screenshot_dir, 'avg_availability_neighbourhood.png'), dpi=300, bbox_inches='tight')
plt.close()
print("✓ avg_availability_neighbourhood.png saved")

plt.figure(figsize=(10, 8))
correlation = df[['price', 'minimum_nights', 'number_of_reviews', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365']].corr()
sns.heatmap(correlation, annot=True, cmap='coolwarm', center=0, fmt='.2f', square=True)
plt.title('Correlation Heatmap', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.savefig(os.path.join(screenshot_dir, 'correlation_heatmap.png'), dpi=300, bbox_inches='tight')
plt.close()
print("✓ correlation_heatmap.png saved")

print("\nAll visualizations saved to 4_screenshots/")